### ISSUE TITLE
what generates nov-places?

### ISSUE THREAD

**Issue by Trevoke** [mannd/dotemacs#2]
Hi!

You have https://github.com/mannd/dotemacs/blob/master/.gitignore#L40 

The file `nov-places` has recently shown up in my .emacs.d and I have no idea why - it's not obviously something I've changed, so I'm looking for something that generates this file, but it's proving harder than expected.

**Comment by mannd** [comment]
It's a file that holds bookmarks used in nov-mode which is an emacs e-pub reader.  See https://depp.brause.cc/nov.el/ .

**Comment by Trevoke** [comment]
Aaaaah.. Thank you, yes, I think I installed that at some point and then
removed it, which is why I couldn't find anything. Much appreciated. :)
